### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by creatorrr** [creatorrr/turbo-chat#2]
- [x] fix debug to log only the right objects
- [x] parse-based scratchpad
- [x] only yield Result(content, done, needs_input) instead of Assistant or PrefixMessage
- [x] tool-bot @whiterabbit1983 
- [x] state replay @creatorrr
